{% set name = "star" %}
{% set version = "2.7.11b.m0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../
  patches:
    # Fixing shared lib issues
    - patches/0001-do-not-enforce-avx2.patch
    - patches/0002-donotuse_own_htslib.patch
    - patches/0003-create-simd-dispatch.patch

build:
  number: 5
  run_exports:
    - {{ pin_subpackage('star', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - vim
  host:
    - htslib >=1.21
    - zlib
  run:
    - htslib >=1.21

test:
  commands:
    - STAR --version
    - STARlong --version

about:
  home: "https://github.com/alexdobin/STAR"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "An RNA-seq read aligner."


extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - biotools:star
    - usegalaxy-eu:rna_starsolo
    - usegalaxy-eu:rna_star
  recipe-maintainers:
    - mjsteinbaugh
